"""Current-constituent large stock universes frozen before expanded tests."""

NASDAQ_100 = tuple("NVDA AAPL GOOG GOOGL MSFT AMZN AVGO SPCX META TSLA MU WMT AMD ASML INTC CSCO AMAT COST PLTR LRCX NFLX ARM PANW TXN KLAC LIN AMGN CRWD SHOP TMUS ADI PEP MRVL SNDK STX QCOM GILD BKNG WDC ISRG PDD VRTX SBUX FTNT APP ADP ADBE ABNB DASH CEG CDNS CSX MAR MELI INTU CMCSA MNST DDOG ROST CTAS MDLZ SNPS HON REGN ORLY PCAR LITE AEP MPWR WBD BKR NXPI TER FAST ALAB ADSK FANG PYPL HONA XEL CRWV RKLB CCEP FER EXC IDXX NBIS MCHP TTWO ODFL WDAY AXON TRI PAYX KDP ROP MSTR GEHC DXCM KHC ALNY".split())

SP_500_TOP_50 = tuple("NVDA AAPL MSFT AMZN GOOGL AVGO GOOG META MU JPM BRK-B TSLA LLY AMD XOM JNJ V WMT CSCO INTC MA ABBV AMAT COST BAC CAT LRCX GE PLTR UNH CVX PG HD KO MRK GS NFLX PM GEV WFC MS TXN KLAC ORCL LIN IBM SNDK VZ MCD PEP".split())

UNIVERSE_FREEZE_DATE = "2026-08-07"
